storage: ./storage
auth:
  htpasswd:
    file: ./htpasswd
    algorithm: bcrypt
    rounds: 10
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  "@*/*":
    access: $authenticated
    publish: $authenticated
    proxy: NONE
  "**":
    access: $authenticated
    publish: $authenticated
    proxy: NONE
log:
  - { type: stdout, format: pretty, level: trace }
