name: setup-env
description: Initializes environment.

inputs:
  node-version:
    description: Override Node Version
    required: false
    default: ''
  cache-prefix:
    description: Additional cache prefix
    required: false
    default: 'default'

outputs:
  node-version:
    value: ${{ steps.install.outputs.node-version }}
    description: Detected Node version.

runs:
  using: "composite"
  steps:
    - name: Env Vars
      shell: bash
      run: |
        echo "COREPACK_ENABLE_DOWNLOAD_PROMPT=0" >> "$GITHUB_ENV"
        echo "YARN_ENABLE_GLOBAL_CACHE=0" >> "$GITHUB_ENV"
    - name: Detect Node Version
      id: detect-node
      run: |
        if [[ -z "${{ inputs.node-version }}" ]]; then
          echo "version=$(cat .nvmrc | tr -d '\n')" >> $GITHUB_OUTPUT
        else
          echo "version=${{ inputs.node-version }}" >> $GITHUB_OUTPUT
        fi
      shell: bash
    - name: Install NodeJS
      id: install
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      with:
        node-version: ${{ steps.detect-node.outputs.version }}
    - name: Enable Corepack
      run: corepack enable
      shell: bash
    - name: Restore Yarn Cache
      id: yarn-cache
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      with:
        path: |
          .yarn/install-state.gz
          .yarn/cache
          .yarn/unplugged
          .pnp.*
        key: ${{ inputs.cache-prefix }}-${{ hashFiles('yarn.lock') }}-${{ steps.detect-node.outputs.version }}
        restore-keys: |
          ${{ inputs.cache-prefix }}-${{ hashFiles('yarn.lock') }}-
          ${{ inputs.cache-prefix }}-
    - name: Install Yarn Project
      run: yarn install --immutable
      shell: bash
    - name: Create Artifacts Directory
      run: mkdir -p artifacts
      shell: bash
    - name: Configure Git
      env:
        GIT_NAME: ${{ github.actor }}
        GIT_EMAIL: ${{ format('{0}@users.noreply.github.com', github.actor) }}
      run: |
        git config --global user.name "$GIT_NAME"
        git config --global user.email "$GIT_EMAIL"
        git config --global init.defaultBranch main
      shell: bash
