#!/bin/bash

if command -v fnm &>/dev/null; then
    fnm use --corepack-enabled --install-if-missing
elif command -v nvm &>/dev/null; then
    . "${NVM_DIR:-~/.nvm}"/nvm.sh;
    nvm install &>/dev/null;
else
    echo "We recommend installing fnm or nvm to ensure you are on the correct version of NodeJS for this project."
fi

if [[ ! "$*" == *"--no-corepack"* ]]; then
    npm install -g corepack;
fi

yarn && \
    yarn husky && \
    yarn sdks vscode vim &>/dev/null;
