#!/bin/bash

if ! command -v nvm &>/dev/null; then
    echo "Missing nvm.";
    return;
fi

. "${NVM_DIR:-~/.nvm}"/nvm.sh;
nvm install &>/dev/null;

if [[ ! "$*" == *"--no-corepack"* ]]; then
    npm install -g corepack;
fi

yarn && \
    yarn husky && \
    yarn sdks vscode vim &>/dev/null;
